image: maven:3.8.5-jdk-11

stages:
    - build
before_script:
    - pwd

    #- cp -f /home/sharedTo/settings.xml $HOME/.m2/settings.xml

    #- cp -f /home/sharedTo/settings-security.xml $HOME/.m2/settings-security.xml

build_job:
    stage: build
    only:
        - pushes
    script:

        - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=http://srvoptiic.optimissa.into:9000 -Dsonar.login=5f31959cb05db624a1ee7d623339dd631a11066a
    tags:
        - docker 
